
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi


image:
  repository: lscr.io/linuxserver/filezilla
  tag: latest

service:
  port: 3000
  portsecure: 3001 


volumeMounts:
  - name: filezilla-data
    mountPath: /config
volumes:
  - name: filezilla-data
    persistentVolumeClaim:
      claimName: filezilla-data-pvc
