
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

imagePullSecrets:
  - name: your secret docker puller

image:
  repository: lscr.io/linuxserver/filezilla
  tag: latest

service:
  port: 3000
  portsecure: 3001 

route: 
  dns: "your dns"
  namespace: "your namespace"

volumeMounts:
  - name: filezilla-data
    mountPath: /config
volumes:
  - name: filezilla-data
    persistentVolumeClaim:
      claimName: filezilla-data-pvc