apiVersion: v1
kind: Service
metadata:
  name: {{ include "filezilla.fullname" . }}
  labels:
    {{- include "filezilla.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.portsecure }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "filezilla.selectorLabels" . | nindent 4 }}
